### ISSUE TITLE
WIndows specific path causes failure on OSX

### ISSUE THREAD

**Issue by gmp26** [GulinSS/jade-angularjs-brunch#1]
jade-angularjs-brunch/src/index.coffee:98 uses the windows specific path
'_public\js\dontUseMe'

replacing with '_public/js/dontUseMe' makes it work on OSX, but I guess this bit is a work in progress anyway. 

Maybe it's enough to detect 'dontUseMe'?

**Comment by GulinSS** [comment]
Merged
